name: nasa_apod_app
description: NASA Astronomy Picture of the Day App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_format: ^1.0.8
  image_picker: ^0.6.7+2
  flutter_email_sender: ^3.0.1
  html: ^0.14.0+3
  provider: ^4.1.3
  share: ^0.6.4+3
  image_save: ^3.1.1
  photo_view: ^0.9.2
  url_launcher: ^5.4.11
  flutter_widget_from_html: ^0.4.1
  extended_image: ^0.9.0
  shared_preferences: ^0.5.7+3
  connectivity: ^0.4.8
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  assets:
    - assets/images/nasa-logo.png
    - assets/images/placeholder.png
  uses-material-design: true
