name: nasa_apod_app
description: NASA Astronomy Picture of the Day App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_review: ^2.1.2+1
  background_fetch: ^1.1.2
  connectivity: ^3.0.6
  date_format: ^2.0.7
  extended_image: ^6.3.4
  flutter_cache_manager: ^3.3.0
  flutter_email_sender: ^5.2.0
  flutter_local_notifications: ^13.0.0
  flutter_widget_from_html: ^0.9.0+2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  html: ^0.15.1
  image_picker: ^0.8.6
  image_save: ^5.0.0
  image: ^3.3.0
  intl: ^0.18.0
  liquid_pull_to_refresh: ^3.0.1
  material_design_icons_flutter: ^6.0.7096
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  provider: ^6.0.5
  scroll_to_index: ^3.0.1
  share: ^2.0.4
  url_launcher: ^6.1.7
  wallpaper_manager:
    git:
      url: https://github.com/ApoorvaAditya/wallpaper_manager.git

dev_dependencies:
  lint: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: assets/icon/icon.png

flutter:
  assets:
    - assets/icon/icon_small.png
    - assets/images/nasa-logo.png
    - assets/images/placeholder.png
  uses-material-design: true
